
#Postgres Config
[postgres]
        database = "recipes_dev"
        table = "recipes"
        username = "recipes_usr"
        password = "recipes_usr"
        host = "172.26.0.2"
        port = "5432"

[keys]
	PrivateKeyPath = "others/keys/app.rsa"
	PublicKeyPath = "others/keys/app.rsa.pub"

[logConfig]
	Log = "INFO"
	LogDirectory = "others/logs"
	LogFilePrefix = "recipe_log"
	EnableLogTrace = false

